### ISSUE TITLE
gumtree is called with unknown options (as for gumtree-2.1.1)

### ISSUE THREAD

**Issue by imz** [coccinelle/herodotos#1]
I have tried to use `--diff gumtree` (previously, I used `--diff gnudiff`).

There are errors like this:

      606 [         diff.ml 99   ] ERROR - *** FAILURE *** Code: 2  gumtree --output asrc /usr/src/HERODOTOS/INPUT/rpm/4.0.4-alt100.94/rpm/rpmio/rpmpgp.c /usr/src/HERODOTOS/INPUT/rpm/4.0.4-alt100.95.M80P.1/rpm/rpmio/rpmpgp.c | gum2hero Linux.gumtree/4.0.4-alt100.94/rpm/rpmio/rpmpgp.c

Here is what it says:

 $ gumtree --output asrc /usr/src/HERODOTOS/INPUT/rpm/4.0.4-alt100.94/rpm/rpmio/rpmpgp.c /usr/src/HERODOTOS/INPUT/rpm/4.0.4-alt100.95.M80P.1/rpm/rpmio/rpmpgp.c ; echo $?
 ** Unknown sub-command '--output'.
 Available Options:
 -c <2>  Set global property (-c property value). Properties do not need to be prefixed by gumtree.
 -v      Verbose mode
 --help  Display help (this screen)
 
 Available Commands:
 * webdiff: a web diff client
 * cluster: Extract action clusters
 * diff: Dump actions in our textual format
 * jsondiff: Dump actions in the JSON format
 * list: List things (matchers, generators, properties, ...)
 * parse: Parse file and dump result
 * swingdiff: A swing diff client
 * axmldiff: Dump annotated xml tree
 0

I'm using gumtree-2.1.1 from <https://github.com/GumTreeDiff/gumtree> (from 2018-01-29).

**Comment by npalix** [comment]
Can you ask the question on the gumtree side ?
I have not idea of the Gumtree changes underlying the issue.

Thanks.

**Comment by npalix** [comment]
The original option is here.
https://github.com/GumTreeDiff/gumtree/commit/5b019e9e83fac277f215b6120f3f76106a2c3bd1

So the new command should be "axmldiff" command with the "--src" option.
See https://github.com/GumTreeDiff/gumtree/blob/develop/client.diff/src/main/java/com/github/gumtreediff/client/diff/AnnotatedXmlDiff.java
